### ISSUE TITLE
ライセンス不明

### ISSUE THREAD

**Issue by nishidayuya** [tnobuhito/asakusa-haisyo-plugin#1]
ぜひ導入したいのですが，ライセンスが不明です．

どういったライセンスでしょうか．

**Comment by tnobuhito** [comment]
ライセンスについては募集中です。
nishidayuyaさんおすすめのライセンスのプルリクをいただけると助かります。
自由であり、自由である事を強制しすぎないライセンスが望ましいです。

**Comment by nishidayuya** [comment]
ライセンスに強い希望がないということであれば，AsakusaSatelliteと同様のライセンスではいかがでしょうか．
#4 でPRしました．

**Comment by tnobuhito** [comment]
ありがとうございますー☆
